import { FC, ReactNode } from "react";
import cls from "./Main.module.scss";
import Head from "next/head";

interface IMainProps {
  children: ReactNode;
}

export const Main: FC<IMainProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={""}>{children}</div>
    </>
  );
};
